[package]
name = "sona-vm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sona-ast = { path = "../sona-ast" }
sona-bytecode = { path = "../sona-bytecode" }
sona-diagnostics = { path = "../sona-diagnostics" }
sona-modules = { path = "../sona-modules" }
sona-runtime = { path = "../sona-runtime" }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
serde_json = "1.0"

[dev-dependencies]
sona-ir = { path = "../sona-ir" }
sona-parser = { path = "../sona-parser" }
sona-source = { path = "../sona-source" }

[lib]
path = "src/lib.rs"
